name: Update Stoic Quote

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight
  workflow_dispatch:

permissions:
  contents: write  
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Insert Stoic Quote into README
        uses: janthmueller/insert-stoic-quote@main
        with:
          type: "daily"                   # 'daily' or 'random'
          file: "README.md"               # file to update
