name: GitHub Self-Updating Stoic Quote

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual triggering

permissions:
  contents: write    # Grant write permissions to push changes

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get random quote
        run: |
          response=$(curl -s https://stoic-quotes.com/api/quote)
          quote=$(echo "$response" | grep -oP '(?<="text":")[^"]*')
          author=$(echo "$response" | grep -oP '(?<="author":")[^"]*')
          date=$(date +"%A, %B %d, %Y")  # Format the current date
          # Write formatted content to README.md
          echo -e '<h1 align="center">Stoic Quote Of The Day</h1>\n' > README.md
          echo -e "<p align=\"center\"><em>$date</em></p>\n" >> README.md
          echo -e '<p align="center">\n  <em>"'"$quote"'"</em><br>\n  <strong>— '"$author"'</strong>\n</p>' >> README.md
          cat README.md
        timeout-minutes: 2

      - name: Push to repository
        run: |
          git config --global user.name "Jan Müller"
          git config --global user.email "janthmueller@users.noreply.github.com"
          now=$(date)
          git add README.md
          git commit -m "Auto Push on $now"
          git push
